from __future__ import annotations

import json
from typing import Any

from app.agent.state import AgentState


MAX_EVIDENCE_ITEMS = 50
MAX_FIELD_LENGTH = 2000


def _safe_value(value: Any) -> Any:
    """
    Convert tool output into bounded, JSON-safe evidence content.

    Tool results are treated as untrusted data. They are serialized
    only as evidence and never interpreted as instructions.
    """

    if isinstance(value, str):
        return value[:MAX_FIELD_LENGTH]

    if isinstance(value, (int, float, bool)) or value is None:
        return value

    if isinstance(value, list):
        return [_safe_value(item) for item in value[:20]]

    if isinstance(value, dict):
        return {
            str(key)[:200]: _safe_value(val)
            for key, val in list(value.items())[:50]
        }

    return str(value)[:MAX_FIELD_LENGTH]


def build_evidence_context(
    state: AgentState,
) -> AgentState:
    """
    Convert tool results into deterministic E1/E2/... evidence records.

    The evidence IDs are generated by the application, not by the LLM.
    """

    tool_results = state.get("tool_results", {})

    evidence_lines: list[str] = []
    evidence_ids: list[str] = []

    counter = 1

    for tool_name, results in tool_results.items():
        if not isinstance(results, list):
            results = [_safe_value(results)]

        for item in results:
            if counter > MAX_EVIDENCE_ITEMS:
                break

            evidence_id = f"E{counter}"
            evidence_ids.append(evidence_id)

            payload = {
                "evidence_id": evidence_id,
                "tool": tool_name,
                "data": _safe_value(item),
            }

            evidence_lines.append(
                json.dumps(
                    payload,
                    ensure_ascii=False,
                    sort_keys=True,
                )
            )

            counter += 1

        if counter > MAX_EVIDENCE_ITEMS:
            break

    context = "\n".join(evidence_lines)

    return {
        **state,
        "evidence_context": context,
        "evidence_ids": evidence_ids,
    }